# This file is to build,test and push the docker image to ECR, and then deploy it to ECS Fargate

name: Build and Deploy to ECS

on:
  push:
    branches: [ main ]  # Or your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest tests/

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region eu-north-1 | \
          docker login --username AWS --password-stdin 136904910983.dkr.ecr.eu-north-1.amazonaws.com

      - name: Build and tag Docker image
        run: |
          docker build -t f1-prediction .
          docker tag f1-prediction:latest 136904910983.dkr.ecr.eu-north-1.amazonaws.com/f1-prediction:latest

      - name: Push Docker image
        run: |
          docker push 136904910983.dkr.ecr.eu-north-1.amazonaws.com/f1-prediction:latest

      - name: Deploy to ECS
        run: |
          aws ecs update-service \
            --cluster f1-cluster-new \
            --service f1-service \
            --force-new-deployment \
            --region eu-north-1
