# This file is to build,test and push the docker image to ECR, and then deploy it to ECS Fargate

version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Running unit and integration tests..."
      - pytest tests/  # Your unit & integration tests

  build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 136904910983.dkr.ecr.eu-north-1.amazonaws.com
      - echo "Building Docker image..."
      - docker build -t f1-prediction .
      - docker tag f1-prediction:latest 136904910983.dkr.ecr.eu-north-1.amazonaws.com/f1-prediction:latest

  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push 136904910983.dkr.ecr.eu-north-1.amazonaws.com/f1-prediction:latest
      - echo "Updating ECS service..."
      - |
        aws ecs update-service \
          --cluster f1-cluster-new \
          --service f1-service \
          --force-new-deployment \
          --region eu-north-1
      - echo "✅ Deployment triggered at `date`"

artifacts:
  files: '**/*'
