# This file is to build,test and push the docker image to ECR

version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - echo Installing dependencies...

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 136904910983.dkr.ecr.eu-north-1.amazonaws.com

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t f1-prediction .
      - docker tag f1-prediction:latest 136904910983.dkr.ecr.eu-north-1.amazonaws.com/f1-prediction:latest

  post_build:
    commands:
      - echo Running tests...
      - docker run --rm f1-prediction python3 -m unittest discover -s tests
      - echo Pushing the Docker image to ECR...
      - docker push 136904910983.dkr.ecr.eu-north-1.amazonaws.com/f1-prediction:latest
artifacts:
  files:
    - '**/*'
